/*
 * This file is generated by jOOQ.
 */
package com.cwt.task.table.jooq.entity;


import org.jooq.Catalog;
import org.jooq.Table;
import com.cwt.task.table.jooq.entity.tables.Regulardata;
import com.cwt.task.table.jooq.entity.tables.SqliteSequence;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>regulardata</code>.
     */
    public final Regulardata REGULARDATA = Regulardata.REGULARDATA;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public final SqliteSequence SQLITE_SEQUENCE = SqliteSequence.SQLITE_SEQUENCE;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Regulardata.REGULARDATA,
            SqliteSequence.SQLITE_SEQUENCE);
    }
}
