/*
 * This file is generated by jOOQ.
 */
package com.cwt.task.table.jooq.entity;


import com.cwt.task.table.jooq.entity.tables.Regulardata;
import org.jooq.TableField;
import org.jooq.UniqueKey;

import com.cwt.task.table.jooq.entity.tables.records.RegulardataRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RegulardataRecord> PK_REGULARDATA = Internal.createUniqueKey(Regulardata.REGULARDATA, DSL.name("pk_regulardata"), new TableField[] { Regulardata.REGULARDATA.ID }, true);
    public static final UniqueKey<RegulardataRecord> SQLITE_AUTOINDEX_REGULARDATA_1 = Internal.createUniqueKey(Regulardata.REGULARDATA, DSL.name("sqlite_autoindex_regulardata_1"), new TableField[] { Regulardata.REGULARDATA.ID }, true);
}
