/*
 * This file is generated by jOOQ.
 */
package com.cwt.task.table.jooq.entity;


import com.cwt.task.table.jooq.entity.tables.Regulardata;
import com.cwt.task.table.jooq.entity.tables.SqliteSequence;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>regulardata</code>.
     */
    public static final Regulardata REGULARDATA = Regulardata.REGULARDATA;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = SqliteSequence.SQLITE_SEQUENCE;
}
