/*
 * This file is generated by jOOQ.
 */
package com.cwt.task.table.jooq.entity.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import com.cwt.task.table.jooq.entity.tables.Regulardata;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RegulardataRecord extends UpdatableRecordImpl<RegulardataRecord> implements Record6<Integer, String, String, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>regulardata.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>regulardata.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>regulardata.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>regulardata.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>regulardata.comment</code>.
     */
    public void setComment(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>regulardata.comment</code>.
     */
    public String getComment() {
        return (String) get(2);
    }

    /**
     * Setter for <code>regulardata.amount</code>.
     */
    public void setAmount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>regulardata.amount</code>.
     */
    public Integer getAmount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>regulardata.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>regulardata.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>regulardata.updated</code>.
     */
    public void setUpdated(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>regulardata.updated</code>.
     */
    public LocalDateTime getUpdated() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Regulardata.REGULARDATA.ID;
    }

    @Override
    public Field<String> field2() {
        return Regulardata.REGULARDATA.NAME;
    }

    @Override
    public Field<String> field3() {
        return Regulardata.REGULARDATA.COMMENT;
    }

    @Override
    public Field<Integer> field4() {
        return Regulardata.REGULARDATA.AMOUNT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Regulardata.REGULARDATA.CREATED;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Regulardata.REGULARDATA.UPDATED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getComment();
    }

    @Override
    public Integer component4() {
        return getAmount();
    }

    @Override
    public LocalDateTime component5() {
        return getCreated();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdated();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getComment();
    }

    @Override
    public Integer value4() {
        return getAmount();
    }

    @Override
    public LocalDateTime value5() {
        return getCreated();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdated();
    }

    @Override
    public RegulardataRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public RegulardataRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public RegulardataRecord value3(String value) {
        setComment(value);
        return this;
    }

    @Override
    public RegulardataRecord value4(Integer value) {
        setAmount(value);
        return this;
    }

    @Override
    public RegulardataRecord value5(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public RegulardataRecord value6(LocalDateTime value) {
        setUpdated(value);
        return this;
    }

    @Override
    public RegulardataRecord values(Integer value1, String value2, String value3, Integer value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RegulardataRecord
     */
    public RegulardataRecord() {
        super(Regulardata.REGULARDATA);
    }

    /**
     * Create a detached, initialised RegulardataRecord
     */
    public RegulardataRecord(Integer id, String name, String comment, Integer amount, LocalDateTime created, LocalDateTime updated) {
        super(Regulardata.REGULARDATA);

        setId(id);
        setName(name);
        setComment(comment);
        setAmount(amount);
        setCreated(created);
        setUpdated(updated);
    }
}
